### PR TITLE
Added merge strategy to allow selecting columns to upsert.

### LINKED ISSUE #4106: Overriding only some merge fields
# Environment

Knex version: 0.21.12
Database + version: pg@latest
OS: Ubuntu 20.04

tagging @nicoburns (thanks for implementing upsert!!)

# Feature discussion / request

1. Explain what is your use case
I'm trying to use the `.onConflict().merge()` but allow partial overrides of the fields. The sql I'm trying to achieve is this:
```sql
INSERT INTO mytable
    (key_field, use_update_field)
    VALUES
    (?, ?)
ON CONFLICT (key_field) DO
UPDATE SET
    use_update_field = EXCLUDED.use_update_field,
    another_constant_field = 'some constant string'
RETURNING *
```
As you can see, in the update part, I'm mixing the `EXCLUDED` fields with a non-excluded field; I tried:
```javascript
knex('mytable')
.insert({key_field: 1, use_update_field: "VALUE"})
.onConflict('key_field')
.merge({ another_constant_field: "some constant string" });
```
However, this will prevent the `use_update_field = EXCLUDED.use_update_field,` from being present.

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work
I think the `.merge()` method could take a second parameter for overrides, eg:
```javascript
.merge(updates, overrides)
```
where the `updates` field could be null/undefined such that:
```javascript
insert({k:1, field: 2}).onConflict('k').merge(null, { some_field: "value" })
///->
// ... UPDATE SET field = EXCLUDED.field, some_field = "value"
```

*edit:
My current workaround (assuming I'm not missing something obvious) is to repeat all the fields in the `.merge()` and use `knex.raw('EXCLUDED.??', 'field_name')`, eg:
```javascript
insert({k:1, field: 2}).onConflict('k').merge({
    field: knex.raw('EXCLUDED.??' ,'field'),
    some_field: "value" 
})
```

* edit2:
I think this is the (3) feature request from #4101

### LINKED ISSUE #4209: Feature request:  Added functionality for onConflict / upsert query building (PostgresSQL)
# Environment

Knex version: 0.21.12
Database + version: PostgresSQL

# Feature discussion / request

1. I am running into what I think is a limitation of the `onConflict`.  In PostgresSQL I want to do an batch upsert like ...
```
knex('tableName')
  .insert(
    { email: "john@example.com", name: "John Doe", occupation: "dev" },
    { email: "jane@example.com", name: "Jane Doe", occupation: "doctor" },
    { email: "alex@example.com", name: "Alex Doe", occupation: "dentist" },
  )
  .onConflict('email')
  .merge(['email', 'name'])
``` 

and have the generated sql be like: 

```
'insert into "tableName" ("email", "name", "occupation", "relationships") values (?, ?, ?) on conflict ("email") do update set "email" = excluded."email", "name" = excluded."name"
```

Right now this is not possible AFAICT, and it's frustrating because the only option is a full merge, but I just want to trim off the extra clause that would be included `"occupation" = excluded."occupation"`.  The optional data param that can be passed to merge works if its a upsert of a single row, but is insufficient for this batch scenario 

2. Explain what kind of feature would support this

For PostgresDB at least, support passing in an array to merge.  Or have a method like `mergeFields` that accepts an array and is only available for certain dbs, similar to how chaining the WHERE clause after merge is itself specific to certain dbs. 

3. Give some API proposal, how the feature should work
```
knex('tableName')
  .insert(
    { email: "john@example.com", name: "John Doe", occupation: "dev" },
    { email: "jane@example.com", name: "Jane Doe", occupation: "doctor" },
    { email: "alex@example.com", name: "Alex Doe", occupation: "dentist" },
  )
  .onConflict('email')
  .mergeFields(['email', 'name'])
``` 

generates: 

```
'insert into "tableName" ("email", "name", "occupation", "relationships") values (?, ?, ?) on conflict ("email") do update set "email" = excluded."email", "name" = excluded."name"
```

### PR DESCRIPTION
**Pull request by MattGson**
Fixes #4209 
Maybe fixes #4106

New syntax on merge:

```
knex('upsert_tests')
          .insert(
            { email: 'mergedest@example.com', name: 'SHOULD BE USED', age: 12 },
          )
          .onConflict('email')
          .merge(['name', 'age'])
```
Will update only the name and age fields.
Also works for multi-inserts.

### CODE REVIEW

**Comment by kibertoad** [comment]
@nicoburns Does this change make sense to you?

**Comment by kibertoad** [comment]
Could you please add documentation for this to https://github.com/knex/documentation?

**Comment by nicoburns** [comment]
@kibertoad 

I think it broadly does. I can definitely see the use case for this. It would be even better if you could mix and match this style with the existing style. Something like:

```javascript
knex('upsert_tests')
          .insert(
            { email: 'mergedest@example.com', name: 'SHOULD BE USED', age: 12 },
          )
          .onConflict('email')
          .merge(['name', { age: 13 }])
```

But I believe that could be added backwards compatibly on top of this PR at a later date if desired.

**Comment by kibertoad** [comment]
@MattGson Any chance you could update documentation for this change, so that it could be merged?

**Comment by MattGson** [comment]
@kibertoad I've added a docs PR [here](https://github.com/knex/documentation/pull/307)

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks!

**Pull request merged**
