### PR TITLE
Implement partial index support

### LINKED ISSUE #657: Conditional index in a migration
Is it possible to specify a condition index when creating table in a migration? Something that would result in the following index:

```sql
create index category_score_id on products(category, score desc, id desc) where active;
```

Thank you.

### PR DESCRIPTION
**Pull request by brandonramirez**
Partial/filtered indexes for Postgres, SQLite and Microsoft SQL Server.

Some of the SQL Server integration tests fail, even without this change.  They appear to be existing issues.

I attempted to implement this feature for Oracle too, but getting connectivity to Oracle from my development environment is a nightmare.  Even in the CI environment, Oracle client installation fails intermittently, so I decided to keep my hands out of Oracle.

MySQL and MariaDB do not support this feature, so I did not attempt to implement it there.

There are still outstanding test failures (I think all due to the above issues), so the Travis CI builds keep failing.  I have verified that this feature does not introduce any new test failures.

Fixes #657

### CODE REVIEW

**Comment by elhigu** [comment]
I'll fix those oracle tests when I have some time. They just must be changed so that only node 4,6 and 8 are tested with oracle. Thanks for the PR though! I'll check this PR when I have some time in my hands.

**Comment by elhigu** [comment]
I got CI fixed up. Could you please rebase this?

**Comment by brandonramirez** [comment]
Sorry, been on other things.  Working on that now.

**Comment by brandonramirez** [comment]
I connected an upstream remote to my fork and merged changes from the upstream master into the feature branch.  Now the CI tests pass.  I think your fix was successful.

**Comment by brandonramirez** [comment]
Documentation PR: https://github.com/knex/documentation/pull/82

**Comment by elhigu** [comment]
Btw. I just noticed that this feature seems to require passing builder instance to tell how partial index should be created. does the alternative `(builder) => builder.whereRaw()` syntax work too?

**Comment by brandonramirez** [comment]
I’m not sure what you mean exactly.  It supports knex.raw if that is what you mean.

There are test cases which uses knex.raw to attach a raw SQL predicate to an index.

**Comment by elhigu** [comment]
I mean that usually knex APIs allow passing builder in following formats:

```js
// query builder
table.index(['foo', 'bar'], 'baz', knex.whereNotNull('email'));

// builder callback arrow function style
table.index(['foo', 'bar'], 'baz', builder => builder.whereNotNull('email'));

// builder callback normal function + this style
table.index(['foo', 'bar'], 'baz', function () { this.whereNotNull('email') });

// raw query builder
table.index(['foo', 'bar'], 'baz', knex.raw('where ?? IS NOT NULL', ['email']));
```

**Comment by brandonramirez** [comment]
Ok I' not familiar with those approaches.  I'll test them out.

**Comment by brandonramirez** [comment]
I understand what you're asking now.  `knex.whereIn`, `whereExists`, etc. use this builder callback pattern.  I'm tracing back to see how it works.  The magic appears to be in the "compileCallback" method.  I may need to refactor the approach to follow this standard.  I'll keep working at it in my spare time.

Do you consider this a blocker for the PR?  (I totally understand if you do - I am new to knex so am not a good judge of where things are).

I just had an addition to my family yesterday so I'm not sure how much time I will have to work on this.  Just looking to gauge how important it is to enhance this now versus later.

**Comment by kibertoad** [comment]
@elhigu Considering that this suppost MSSQL/Postgres/SQLite, isn't that plenty already? We have some features that not work in all DBs already anyway. Would it make sense to merge this one after syncing with master or there is something left to be done?

**Comment by elhigu** [comment]
If it is possible to implement for mysql / mssql too, it would be better. If it just is not possible, then throwing an error is fine. Also good integration tests would be good to have to verify that feature works consistently between dialects. For example with forUpdate / forShare and and unique index behaviour had to be tuned quite a lot at some point, where I added integration tests that those features acutally behaved the same way between dialects (with .unique constraint IIRC the behaviour with NULL values was the quite different in some DBs).

**Comment by elhigu** [comment]
Also being able to support those other normal ways to pass the predicates is must to have. Currently only passing query builder was supported https://github.com/tgriesser/knex/pull/2401#issuecomment-366152298

**Comment by brandonramirez** [comment]
I did implement support for MS SQL Server.  And it has integration tests.  However, MySQL support is impossible because MySQL does not support partial indexes.

**Comment by smithaitufe** [comment]
Hi folks, what is the state of this PR?

**Comment by kibertoad** [comment]
@smithaitufe There are merge conflicts all over the place. If someone resolves them and addresses the comments, this can be merged.

**Comment by dvalsagna89** [comment]
someone, please resolve those conflicts. I need this!

**Comment by kibertoad** [comment]
@dvalsagna89 Would you like to do that?

**Comment by dvalsagna89** [comment]
@kibertoad i'd do it

**Comment by dvalsagna89** [comment]
i solved the conflicts but i'm not able to push them. not sure how to do it. never collaborated before 😄

**Comment by kibertoad** [comment]
@dvalsagna89 I don't think you can push to someone else's fork. Create your own fork, push there and create a new PR.

**Comment by brandonramirez** [comment]
Is this something I can grant access to? I’d be happy to share my branch.

**Comment by kibertoad** [comment]
@brandonramirez You'd have to add @dvalsagna89 as a collaborator to your fork.

**Comment by dvalsagna89** [comment]
@brandonramirez may be better if you solve the conflicts and push. are not to many

**Comment by kibertoad** [comment]
@dvalsagna89 There are some outstanding comments beyond just conflicts, though.

**Comment by brandonramirez** [comment]
@dvalsagna89 I added you as a collaborator to my fork repo. I don't have time to resolve merge conflicts right now unfortunately.

**Comment by OlivierCavadenti** [comment]
Superseded by #4768

**Pull request closed without merging**
