### PR TITLE
Print help only when there are no arguments

### PR DESCRIPTION
**Pull request by yeonhoyoon**
knex cli should print help only when there are no arguments.
current implementation always prints help even when given correct arguments, such as `knex migrate:status`.
the correct way to check argument length is via process.argv.
reference: https://github.com/tj/commander.js/#outputhelpcb

### CODE REVIEW

**Comment by timorthi** [comment]
+1 also running into this, looks like a regression from #3604

**Comment by kibertoad** [comment]
I'll take a look tomorrow, thanks. One quick note: could you please add cli-testlab-based test for this?

**Comment by yeonhoyoon** [comment]
OK, but I'm not familiar with `cli-testlab`, so I will need some time to look into it.

**Comment by kibertoad** [comment]
@yeonhoyoon Here is a super simple example: https://github.com/knex/knex/blob/master/test/cli/version.spec.js

and you can check other files in same directory if you'd need more than that

**Comment by yeonhoyoon** [comment]
@kibertoad 
Thanks for your feedback, I added some specs to test help command.
There wasn't an assertion helper in the `cli-testlab` for expecting the output to _not include_ a given string, so I used the raw stdout variable instead to test the desired behavior.

**Comment by kibertoad** [comment]
Much appreciated!

There are linting errors in the test:
```
/home/travis/build/knex/knex/test/cli/help.spec.js
   6:7  error  'cliPkg' is assigned a value but never used  no-unused-vars
  30:7  error  'expect' is not defined                      no-undef
```

After those are fixed, this can be merged :)

**Comment by kibertoad** [comment]
@yeonhoyoon BTW, thank you for mentioning missing functionality in `cli-testlab`. I've added `notExpectedOutput` parameter and published 1.9.0, but it's a small thing, feel free to update it or leave as it is.

**Comment by yeonhoyoon** [comment]
@kibertoad 
Apologies for leaving unused variables in the code, and thanks for quickly adding features to `cli-testlab`. I've changed the tests to use the newly added functionality. 
Please let me know if you have any other feedback.

**Comment by kibertoad** [comment]
Thanks! <3

**Comment by kibertoad** [comment]
Released in 0.20.8

**Pull request merged**
