### PR TITLE
Global table definitions v2

### PR DESCRIPTION
**Pull request by artursvonda**
Fixed the Typescript issues in the first PR.

Had to change imports a bit since there are issues with mixing modern and commonjs exports. Will update docs as well.

### CODE REVIEW

**Comment by artursvonda** [comment]
Docs update https://github.com/knex/documentation/pull/294

**Comment by artursvonda** [comment]
Figured out a way to do it without API change (closed Docs PR)

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks a lot!

**Comment by kibertoad** [comment]
Released in 0.21.12

**Pull request merged**
