### PR TITLE
Update type definition for WhereIn

### PR DESCRIPTION
**Pull request by iceflash**
Update type definition for WhereIn for mixed value and query builder

### CODE REVIEW

**Comment by iceflash** [comment]
@lorefnon can you review this PR?

**Comment by kristiandupont** [comment]
I'd like to see this merged if possible..

**Comment by kibertoad** [comment]
@kristiandupont Can you confirm that you tested this change and it works?

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks!

**Comment by kibertoad** [comment]
Released in 0.21.13

**Pull request merged**
