### PR TITLE
Missing comments on delete, update and insert

### PR DESCRIPTION
**Pull request by sebastienroul**
Few monthes ago comments where included in query, but only in select statement. Here is the code to make delete, update and insert compatible with comments

### CODE REVIEW

**Comment by kibertoad** [comment]
@sebastienroul could you please add tests?

**Comment by sebastienroul** [comment]
@kibertoad  Hi, yes sure, but can you give me pointer to the test written for the select statement please, I cant find them (µI'd like to use them as template). For your info PR is working like a charm on 10 of our projects :)

**Comment by sebastienroul** [comment]
@kibertoad : Finally, unit test + integration test are there.
I clear my first attempt to modify all dialect, and focus only on MYSQL. Everything is green... let pull :)

**Comment by kibertoad** [comment]
thanks!

**Pull request merged**
