### PR TITLE
fix help text being printed twice (#4072)

### PR DESCRIPTION
**Pull request by emilwihlander**
When the cli is called without arguments it prints the help text twice. This pull request makes it print it only once. See issue #4072

### CODE REVIEW

**Comment by kibertoad** [comment]
Could you please add CLI test for this?

**Comment by emilwihlander** [comment]
I looked at it but with the library used to test the cli there was no easy way to check if something appears multiple times as far as I could see. The tests do test whether or not it prints at least once at the moment and it may be overkill to add a complicated test for a bug that doesn't have any function-breaking effect.

**Comment by kibertoad** [comment]
@emilwihlander Wouldn't `notExpectedOutput` with duplicated text do the trick?

**Comment by emilwihlander** [comment]
By using something like `notExpectedOutput: ['usage', 'usage']`?

My understanding of the cli-testlab library is that if you specify multiple strings for `notExpectedOutput` it checks if any of the strings exist rather than if all exist. Therefore I don't find a reasonable way to test for multiple occurrences.

This is the function used by the library:
```
function assertNotOutput(
  stdout: string,
  notExpectedOutput: string[] | string | undefined,
  rejectFn: (error: AssertionError) => void
) {
  const notExpectedOutputs = toStringArray(notExpectedOutput)

  const errors: string[] = []
  if (notExpectedOutputs && notExpectedOutputs.length > 0) {
    notExpectedOutputs.forEach((notExpectedEntry: string) => {
      if (stdout.includes(notExpectedEntry)) {
        errors.push(`Expected output not to include "${notExpectedEntry}", but it was actually "${stdout}"`)
      }
    })
  }
  if (errors.length > 0) {
    rejectFn(new AssertionError(errors.join('\n')))
  }
}
```

**Comment by kibertoad** [comment]
@emilwihlander Can't this be done by using one single long assertion?

**Comment by kibertoad** [comment]
If not, I will extend cli-testlab to support occurrence counting.

**Comment by emilwihlander** [comment]
I could add the entire help text printed plus ` + '\nusage'`, I guess. The test would break (always succeed) if the help text would be changed though since the specific help text would never match again. That isn't desirable.

**Comment by emilwihlander** [comment]
You could either add a flag (maybe `expectedOutputOnce`?) or extend the current option to accept a object to specify the number of times a string should occur, e.g. `expectedOutput: {'usage': 1}` to make the checking easier :)

**Comment by emilwihlander** [comment]
I just thought of a possible workaround, 
```
it('Prints help when no arguments are given', () => {
  return execCommand(`node ${KNEX}`, {
    expectedErrorMessage: 'Process exited with error',
    expectedOutput: 'Usage',
    notExpectedOutput: '\nUsage',
  });
});
```
should work right? I don't have the test suite running on my computer so I can't test locally, could you try @kibertoad?

**Comment by kibertoad** [comment]
@emilwihlander Ended up extending cli-testlab to have more explicit assertions, let's see if CI passes now :)

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thank you!

**Pull request merged**
