### PR TITLE
Add DPI error codes for Oracle

### PR DESCRIPTION
**Pull request by vpeltola**
Add DPI-1010 and DPI-1080 error codes required for oracledb >=5.2.0

### CODE REVIEW

**Comment by kibertoad** [comment]
@cjbj Does this look correct?

**Comment by cjbj** [comment]
@kibertoad by eyeball, it seems fine.  The full error number list is a bit over-the-top (and wouldn't be needed for new code that targets node-oracledb 5.2+), but if this case statement is only checked on error conditions, there isn't any harm.  

I would question whether NJS-040 should be on the list - there is no connection in this case.

**Comment by kibertoad** [comment]
@vpeltola Can you drop the NJS-040?

**Comment by vpeltola** [comment]
Removed NJS-040 as requested.

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks!

**Comment by kibertoad** [comment]
Released in 0.95.8

**Pull request merged**
