### PR TITLE
add analytic functions

### PR DESCRIPTION
**Pull request by atiertant**
add analytic functions (only works on mssql, oracle and postgresql):
- denseRank()
- rank()
- rowNumber()

doc [here](https://github.com/knex/documentation/pull/5)

### CODE REVIEW

**Comment by tgriesser** [comment]
Thanks for the PR... going to take a look at this one for a bit. I'd like to see if there'd be a simpler way to augment the query building process without adding a ton of extra dialect specific methods to the core builder chaining api.

Perhaps something like #1647 is the best answer for the 5% of queries that don't fit well with the builder, I'd like to get that into a release fairly soon.

**Comment by atiertant** [comment]
@tgriesser hi, have you got some news on it? we needs this feature on our developement, is there something we could do for this PR?

**Comment by kibertoad** [comment]
@tgriesser @elhigu So what was the verdict on this one?

**Comment by elhigu** [comment]
I have no comments or preference if I would like knex to have these or not.

**Comment by kibertoad** [comment]
@atiertant I realize that this was ages ago and probably this feature is no longer relevant for you, but in case you would be willing to rebase it against current master, it can go in.

**Comment by kibertoad** [comment]
Merged as #4188

**Pull request closed without merging**
