### PR TITLE
Introduce the "infamous triplet" export

### PR DESCRIPTION
**Pull request by kibertoad**
This allows users to import knex in a variety of ways, as a default or a named import, using ES6 imports or CommonJS. Makes forcing `esModuleInterop` unnecessary. Allows to clearly separate between `knex` as function that user calls, and `Knex` as namespace and interface for knex builder.

### CODE REVIEW

**Comment by kibertoad** [comment]
@felixmosh This breaks dynamic typing for custom QueryBuilder extensions from #3334, could you by any chance take a look?

**Comment by felixmosh** [comment]
I think that the augmentation of the module should be like this:

```ts
declare module '../types' {
  namespace Knex {
    interface QueryBuilder {
      customSelect<TRecord, TResult>(
        value: number
      ): Knex.QueryBuilder<TRecord, TResult>;
    }
  }
}
```

**Comment by kibertoad** [comment]
@felixmosh Thanks a lot, that worked!

**Comment by kibertoad** [comment]
@lorefnon @elhigu Thoughts on this change?

**Comment by lorefnon** [comment]
Looks good to me. Seems like something that make life of some people easier. 

Although when using typescript this is seldom a real problem because TS would usually do the right thing for you.

**Pull request merged**
