### PR TITLE
This allows the user to set their own lock table name

### PR DESCRIPTION
**Pull request by krainboltgreene**

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Point me to where I neeed to change docs, if this is accepted.

**Comment by elhigu** [comment]
@krainboltgreene change looks good, what is missing is the documentation to index.html and test case to make sure that feature really works.

**Comment by krainboltgreene** [comment]
@elhigu Any chance you could write the test or at least point me to a recent pull request that deals with this area and has a test?

**Comment by elhigu** [comment]
@krainboltgreene You can start looking to tests here: https://github.com/tgriesser/knex/blob/master/test/integration/suite.js

Thats where migration tests are getting their configuration and knex instance is passed to here: https://github.com/tgriesser/knex/blob/master/test/integration/migrate/index.js

Where you should be able to add tests case for changing the migration lock table name. 

Even better would be if you can find somewhere a test where changing name of the migration table is tested it would be pretty perfect example. I'm just not sure if that has been tested at all :(

Hope that these pointers gets you started.

**Comment by kibertoad** [comment]
@elhigu Would this change be still good to go if I added test and documentation?

**Comment by elhigu** [comment]
Yep, it would be

**Comment by kibertoad** [comment]
why was this deleted? it just missed tests

**Comment by krainboltgreene** [comment]
I don't care anymore.

**Pull request closed without merging**
