### PR TITLE
Fix orWhereJsonPath clause

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
- Closes https://github.com/knex/knex/issues/5020

### CODE REVIEW

**Comment by OlivierCavadenti** [comment]
> this is not a breaking change?

No, a parameter is missing in whereJsonPath so orWhereJsonPath doesn't work.

**Comment by kibertoad** [comment]
are types correct?

**Comment by OlivierCavadenti** [comment]
> are types correct?

Yes, interfaces are the same for all 3 functions: 

image

**Comment by kibertoad** [comment]
Released in 1.0.4

**Pull request merged**
