### PR TITLE
Fix isModuleType() for yarn (#4447)

### PR DESCRIPTION
**Pull request by lehni**
This relates to the issues #4447, #4295, #4158

I encounter the same problem as #4447 in an ESM project that uses yarn instead of NPM.

~~My proposed PR keeps the check for `process.env.npm_package_type` because it's faster than `await getPackageType(filepath)) === 'module'` and to avoid possible breakage on projects that somehow rely on it, but in a future one could move entirely away from that and it should still work.~~

**Update:** I found out it's best to not rely on `process.env.npm_package_type` at all and use a very simple, sturdy implementation that also solves more scenarios in which `--esm` previously lead to failures:

```js
async function isModuleType(filepath) {
  return (
    filepath.endsWith('.mjs') ||
    (!filepath.endsWith('.cjs') &&
      (await getPackageType(filepath)) === 'module')
  );
};
```

### CODE REVIEW

**Comment by kibertoad** [comment]
@lehni Some unit tests are failing

**Comment by lehni** [comment]
@kibertoad I'm looking into it right now. As far as I can tell by now, it looks like my change makes the `--esm` CLI argument redundant and correctly figures out how to import files without it. So the tests that are expected to fail don't fail anymore.

How shall we deal with it?

**Comment by lehni** [comment]
@kibertoad it doesn't make `--esm` fully redundant, but it does make more situations work, which I've now reflected in the updated tests. Please take a look.

**Comment by lehni** [comment]
@kibertoad all green! 🎉

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks a lot!

**Comment by lehni** [comment]
@kibertoad you're welcome, happy to help! Thank you for merging so quickly!

**Comment by andrewchilds** [comment]
Hi @lehni and @kibertoad! After upgrading Knex from 1.0.2 to 1.0.7, I was having trouble running migrations locally, and tracked it down to this PR. I use yarn, ESM, and `.js` file extensions in my project.

Here's the command I've been using:

```
node_modules/knex/bin/cli.js migrate:up --esm --knexfile ./path/to/knexfile.js
```

Knex would evaluate the next migration file, but not actually execute the `up` command. I finally realized that by removing the `--esm` flag, the migration would run. This seems at odds with the knexjs documentation at https://knexjs.org/#esm-interop. What is the behavior of `--esm` flag in Knex 1.0.5 and newer? I'm happy to help update the documentation, but not sure what the new behavior is.

btw - @lehni I've been a fan of your work for many years! And @kibertoad, thank you for maintaining this extremely useful library.

**Comment by lehni** [comment]
@andrewchilds I may be wrong, but I believe `--esm` is now only needed to support esm migrations from a non-ESM project. It's been a while since I wrote this PR and I already forgot the details, which are rather complex :)

I'd recommend creating a separate issue to make sure this gets addressed in the docs...

PS: Thanks for the kind words on my work!

**Comment by lehni** [comment]
Yes it's indeed like this. This code here is from the tests:

```js
const fixture = [
  /** MIGRATIONS */
  {
    title: 'migrates esm modules',
    testCase: 'knexfile-esm',
    knexArgs: ['migrate:latest', '--esm'],
    dropDb: true,
    expectedOutput: 'Batch 1 run: 1 migrations',
    expectedSchema: [
      'knex_migrations',
      'sqlite_sequence',
      'knex_migrations_lock',
      'xyz',
    ],
  },
  {
    title: 'migrates esm modules from a module',
    testCase: 'knexfile-esm-module',
    knexArgs: ['migrate:latest'],
    expectedOutput: 'Batch 1 run: 1 migrations',
    dropDb: true,
    expectedSchema: [
      'knex_migrations',
      'sqlite_sequence',
      'knex_migrations_lock',
      'xyz',
    ],
  },
```

See how the first fixture (`knexfile-esm`) needs it, and the second (`knexfile-esm-module`) doesn't?  It's the second that provides `"type": "module"` in its `package.json` file.

**Comment by andrewchilds** [comment]
Thank you @lehni for the detailed reply! I'll open a new issue about clarifying the docs related to the `--esm` flag. Cheers.

**Pull request merged**
