### PR TITLE
Inconsistencies between .select and .returning

### PR DESCRIPTION
**Pull request by LucasHFS**
attempt to solve #2544 and make the #2337 functionality work

### CODE REVIEW

**Comment by LucasHFS** [comment]
Yes, I was searching for something to contribute with. I started by this #2544. Then I saw #2337 after a few days that this PR covers.

**Comment by LucasHFS** [comment]
Searching for issues to solve, This PR solves #2571 as well

**Comment by fdevibe** [comment]
I would really appreciate it if this was merged. As described in #2571, this also prevents returning geometry in a usable format, like with `ST_AsGeoJSON()` (AFAICT).

**Comment by kibertoad** [comment]
I'll look into this in the upcoming weeks. Considering that Objection still hasn't updated to the latest semver major, I think there is still space to squeeze in another breaking change.

**Comment by kibertoad** [comment]
@OlivierCavadenti Can you take this one?

**Comment by kibertoad** [comment]
@OlivierCavadenti That happens if you rerun migration after deleting some migration files that were run previously. Consider deleting knex changelog table

**Comment by kibertoad** [comment]
[object] thing looks very sus, though, probably we broke logging after changing migration file structure, but maybe it comes from other branch being used before

**Comment by kibertoad** [comment]
ah, so ci has it too. guess we broke migrator logic for fetching previously ran migrations

**Comment by OlivierCavadenti** [comment]
> ah, so ci has it too. guess we broke migrator logic for fetching previously ran migrations

... in fact I miss to report one test correction with the rebase... now seems good (excepted Lint issue)

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
@OlivierCavadenti Incredible work, thank you so much! I will fix the linting issue tomorrow myself.
Do we need to update documentation after this change?

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Incredible work, thank you so much! I will fix the linting issue tomorrow myself. Do we need to update documentation after this change?

Sure : https://github.com/knex/documentation/pull/378

**Comment by kibertoad** [comment]
Released in 1.0.1.

**Pull request merged**
