### PR TITLE
Active Coveralls on Pull Requests

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
- Active existing coveralls Github Action on pull requests to have code coverage control (avoid no covered code)

### CODE REVIEW

**Comment by OlivierCavadenti** [comment]
@kibertoad It seems coverall bot dont leave comment on the PR, can you check this ?
https://javascript.plainenglish.io/enable-coveralls-to-leave-comments-on-prs-4c88fbeee363

**Comment by OlivierCavadenti** [comment]
@kibertoad 
I made some tests, and it seems at this time it will be difficult to automate posting comments on PR with coveralls (write permissions issue), it's not so important by the way.
One thing I will like by the way is to have a failing job when code coverage drop.

image

I intentionnaly drop the code coverage by skip some tests, but it seems the job is already green.
Can you check in the repo settings of Coveralls if they are any threshold for coverage decrease and remove it ?

**Comment by kibertoad** [comment]
Sorry for delay, will take a l9ok tomorrow

**Comment by kibertoad** [comment]
I've set threshold for change to 0.0

**Comment by OlivierCavadenti** [comment]
Coveralls job still green, but it seems an issue : https://github.com/lemurheavy/coveralls-public/issues/1623

**Comment by OlivierCavadenti** [comment]
Can remove threshold by blank the input instead of put 0.0 plz ? @kibertoad

**Comment by kibertoad** [comment]
@OlivierCavadenti done

**Comment by kibertoad** [comment]
image

**Comment by OlivierCavadenti** [comment]
It's possible to send me credentials for Coveralls by mail ? I will tests some configuration tomorrow.

**Comment by kibertoad** [comment]
@OlivierCavadenti Try using github account for auth, if you can't see knex repo there, I'll add permissions

**Comment by OlivierCavadenti** [comment]
@kibertoad I can connect and I see project but I can't modify anything

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Can you try now?

it's ok now thanks !

**Comment by OlivierCavadenti** [comment]
Seems coverage decrease don't work but it seems to be useful to have the coverage on each pull request anyway. I will check later if I finally can fix this...

**Pull request merged**
