### PR TITLE
Fix Oracle error codes

### PR DESCRIPTION
**Pull request by abskmj**
Updated some of the incorrect Oracle codes (ORA-XXXXX) to correct values.

### CODE REVIEW

**Comment by maximelkin** [comment]
You are fixing old oracle driver (https://www.npmjs.com/package/oracle), is this intended?

**Comment by abskmj** [comment]
The new oracle driver inherits from the old one and is using these codes. Yes, it's intended.

**Comment by kibertoad** [comment]
@abskmj Could you please point me in the direction of reference source you used for correct codes?

**Comment by abskmj** [comment]
This official page has the details: https://docs.oracle.com/cd/B28359_01/server.111/b28278/toc.htm

**Comment by kibertoad** [comment]
Released in 0.20.1

**Pull request merged**
