### PR TITLE
fix: Support nodejs v8 promise typing

### PR DESCRIPTION
**Pull request by alexkvak**

### CODE REVIEW

**Comment by drwatsno** [comment]
Wait.. I think it will break someone who already using this typings :thinking:

**Comment by drwatsno** [comment]
Anyway, could someone please explain this ```Pick<Promise<T>, "then" | "catch" | "etc">``` typing? It looks confusing

**Comment by alexkvak** [comment]
@kibertoad I guess the solution of #3422 was wrong. 

Could you explain why the previous version 
`interface ChainableInterface<T = any> extends Promise<T>`
does the wrong things?

**Comment by lorefnon** [comment]
@alexkvak can you please provide some context on what are you trying to fix ? 

> Wait.. I think it will break someone who already using this typings 🤔

Yes, finally will not be available in QueryInterface where as it is exposed.

**Comment by alexkvak** [comment]
I try to return node v8 support.
If you create new project from scratch with @types/node@8 and latest knex version, you become Typescript compile error.

Sorry, I can’t provide some code just node.

**Comment by lorefnon** [comment]
> Could you explain why the previous version
interface ChainableInterface<T = any> extends Promise<T>
does the wrong things?

So, typescript interfaces are mutable. And it is possible for other packages (like  `@types/bluebird-global` as was the case in https://github.com/knex/knex/issues/3422) to extend global interfaces and add keys etc. You can read more about this feature [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

ChainableInterface (what knex.select etc.) returns is not a Promise, but it exposes *some* promise methods which get [delegated](https://github.com/knex/knex/blob/master/lib/interface.js#L104) to the resolved promise when invoked.

When this happens then `ChainableInterface extends Promise` is wrong because it claims that it is compatible with Promise but in reality it is not. It is only exposing a subset of the methods.

This is usually not a problem in practice, but one case in particular (timeout) is problematic because Bluebird's timeout doesn't match the signature of an identically named function implemented in Knex. 

There shouldn't really be a conflict because Bluebird's timeout is not actually available through QueryInterface even if it was the global Promise. But the conflict arises because of the lax type definition of QueryInterface. 

> Anyway, could someone please explain this Pick<Promise<T>, "then" | "catch" | "etc"> typing? It looks confusing

It is conceptually similar to Lodash.pick. You get only the keys that you pick mapped to the corresponding values:

```
type A = { a: string, b: string, c: string }
type B = Pick<A, "a" | "b">;
// Same as: 

type B = { a: string, b: string }
```

**Comment by lorefnon** [comment]
@alexkvak Can you please share the error that you get ?

**Comment by alexkvak** [comment]
@lorefnon thanks!

**Comment by kibertoad** [comment]
Released in 0.20.2

**Pull request closed without merging**
