### PR TITLE
Test/document esm interop mixed formats (knexfile/migrations/seeds)

### PR DESCRIPTION
**Pull request by D10221**
Test/document esm interop mixed formats combinations
knexfile[.js,cjs,mjs] (commonsjs/esm) 
migrations/ [.js,cjs,mjs]
seeds/ [.js,cjs,mjs]

### CODE REVIEW

**Comment by D10221** [comment]
> 
> mjs knexfile CAN'T provides ESM/js migrations.

I think I found a new can of worms   :(

But honestly, can't see the use of it ....beyond because you should 'can'

**Comment by D10221** [comment]
TODO:  _mjs knexfile CAN'T provides ESM/js migrations when specified to load 'js' extension_

**Comment by D10221** [comment]
@kibertoad 
Hi, 
If https://github.com/knex/knex/pull/3986/commits/159c05be6706fee7059139c78509a911c8f0bcc6 is a pass.
I think it's done

**Comment by kibertoad** [comment]
@D10221 Thanks! Do you think that it might make sense to also add a section about ESM support to https://github.com/knex/documentation?

**Comment by D10221** [comment]
> 
> 
> @D10221 Thanks! Do you think that it might make sense to also add a section about ESM support to https://github.com/knex/documentation?

Yes, 
for example  ... some restrictions are removed from the original feature release.
Like _"knex won't find 'default' export"_,
it works on this version

**Comment by kibertoad** [comment]
@D10221 Would you consider updating https://github.com/knex/documentation/blob/gh-pages/sections/migrations.js and https://github.com/knex/documentation/blob/gh-pages/sections/seeds.js?

**Comment by D10221** [comment]
> 
> 
> @D10221 Would you consider updating https://github.com/knex/documentation/blob/gh-pages/sections/migrations.js and https://github.com/knex/documentation/blob/gh-pages/sections/seeds.js?

👍

**Pull request merged**
