### PR TITLE
Document gotcha for running mssql tests locally

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu Have you ever encountered this issue yourself? Running the code on Windows is the only way how I can explain why it works in CI but fails locally, although I have no idea why it would make a difference for Docker environment.

**Comment by elhigu** [comment]
Nope I have never seen that 🤔

**Comment by kibertoad** [comment]
@elhigu Does it work locally without a hitch for you? Which OS are you running?

**Comment by elhigu** [comment]
I've been using mostly MacOS for knex work, but also I haven't ran mssql (or any other) knex tests for a long time.

**Pull request closed without merging**
