### PR TITLE
Wrapped Unions Fixes

### LINKED ISSUE #5061: Syntax errors when using union with first/limit in 1.0.4
# Environment

Knex version: 1.0.4
Database + version: PostgreSQL 13.4
OS: Debian

# Bug

In 1.0.4 the behavior (order and wrapping) of union changed causing queries that previously worked to generate syntax errors. 

One example is:
```ts
const results = await knex('accounts')
  .select('last_name')
  .unionAll(function () {
    this.select('last_name').from('accounts');
  })
  .first();
expect(results).to.eql({ last_name: 'User' });
```

Which in 1.0.4 gives `error: select "last_name" from "accounts" limit $1 union all select "last_name" from "accounts" - syntax error at or near "union"`.

But in 1.0.3 it generates `select "last_name" from "accounts" union all select "last_name" from "accounts" limit ?`.

Another query that fails is
```ts
const results = await knex
  .unionAll(
    function () {
      this.select('last_name').from('accounts');
    },
    function () {
      this.select('last_name').from('accounts');
    },
    true
  )
  .first();
expect(results).to.eql({ last_name: 'User' });
```

with `error: (select "last_name" from "accounts") union all (select "last_name" from "accounts") (limit $1) - syntax error at or near "("`

I believe this change is introduced in https://github.com/knex/knex/pull/5030. Is this new behavior intended and we should rewrite our union queries?

This following is working, so it's not that hard to update the queries but it seems like a breaking change?
```ts
const results = await knex
  .unionAll(
    function () {
      this.select('last_name').from('accounts');
    },
    function () {
      this.select('last_name').from('accounts');
    }
  )
  .first();
```

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
- Fix errors with wrapped unions.
- Closes #5061
- Related #1630

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
@OlivierCavadenti Are you planning any additional fixes in the nearby future, or can I cut new version after this is merged?

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Are you planning any additional fixes in the nearby future, or can I cut new version after this is merged?

No, in the pipe, (in this order) : finish async / await all query integration files, finish all my opened PR (cast + override connection), then I will dig in open PR to see what we can finish.

**Comment by felixmosh** [comment]
When this fix will be published?

**Comment by kibertoad** [comment]
I'll try to publish new version today.

**Comment by kibertoad** [comment]
Released in 1.0.5

**Pull request merged**
