### PR TITLE
Oracle: replace user_tab_columns with all_tab_columns

### LINKED ISSUE #4041: columnInfo() requires an Owner User in Oracle
# Environment

Knex version: 0.21.5
Database + version: Oracle 12
OS: Windows

# Feature discussion / request

1. Explain what is your use case
When using **columnInfo()** in a development DB I don´t have any problems because I connect with an Owner User. But for production DB we use Service Users, so everytime columnInfo() is executed, it returns zero rows, that causes problems with  mapping.

2. Explain what kind of feature would support this
Internally, '**oracledb**' dialect uses **"user_tab_columns"** that only works if you use an Owner User, but for others users types it does not work.
Oracle dialect should use "**all_tab_columns**", so any user can retrieve table information

### PR DESCRIPTION
**Pull request by torres-federico**
Resolves #4041

### CODE REVIEW

**Comment by elhigu** [comment]
how does this feature work with other dialects between service / owner users? I think this detail of functionality would be worth documenting.

**Comment by torres-federico** [comment]
Ok, I did a little research on the other dialects:

MSSQL / MySQL / PostgreSQL / Redshift: all use **information_schema.columns**. This View only requires a GRANT to be accesible, so you don't need an owner user.

SQLite: uses **PRAGMA table_info()**, it doesn´t require any priveliges.

Oracle: as I explained in #4041, uses **user_tab_columns**. So you're limited to be an owner user only

**Comment by elhigu** [comment]
I suppose changing this then makes the functionality more consistent 👍

**Comment by elhigu** [comment]
re-triggered travis... for some reason knex 14 had failed.

**Comment by elhigu** [comment]
```
1) CLI tests
       esm interop and mjs support
         dynamic importing js file from NON module package is not supported:
     Error: Expected error to include "Unexpected export statement in CJS module", but it was actually "(node:11678) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/travis/build/knex/knex/test/jake-util/knexfile-esm-package/knexfile.js:2
export default {
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:192:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async default (file:///home/travis/build/knex/knex/test/jake-util/knexfile-imports/knexfile2.mjs:8:31)
    at async openKnexfile (/home/travis/build/knex/knex/bin/cli.js:32:14)"
      at new AssertionError (node_modules/cli-testlab/lib/AssertionError.ts:3:5)
      at assertErrorMessages (node_modules/cli-testlab/lib/execution-test-helper.ts:40:14)
      at Exec.<anonymous> (node_modules/cli-testlab/lib/execution-test-helper.ts:109:9)
      at ChildProcess.<anonymous> (node_modules/jake/lib/utils/index.js:227:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
  2) CLI tests
       esm interop and mjs support
         static importing js file from NON module package is not supported:
     Error: Expected error to include "Unexpected export statement in CJS module", but it was actually "(node:11707) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/travis/build/knex/knex/test/jake-util/knexfile-esm-package/knexfile.js:2
export default {
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:192:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async default (file:///home/travis/build/knex/knex/test/jake-util/knexfile-imports/knexfile2.mjs:8:31)
    at async openKnexfile (/home/travis/build/knex/knex/bin/cli.js:32:14)"
      at new AssertionError (node_modules/cli-testlab/lib/AssertionError.ts:3:5)
      at assertErrorMessages (node_modules/cli-testlab/lib/execution-test-helper.ts:40:14)
      at Exec.<anonymous> (node_modules/cli-testlab/lib/execution-test-helper.ts:109:9)
      at ChildProcess.<anonymous> (node_modules/jake/lib/utils/index.js:227:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

@kibertoad have you seen that before?

**Comment by kibertoad** [comment]
@torres-federico @elhigu Yeah, latest changes from master need to be pulled in.

**Comment by torres-federico** [comment]
@kibertoad Thanks for the help!

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thank you for your contribution!

**Pull request merged**
