### PR TITLE
Esm interop tests #3978

### PR DESCRIPTION
**Pull request by D10221**
Extend expand esm modules interop tests (wip)

+ refactor --esm test -> 'esm-interop.spec.js'
+ include not supported, by Node or Knex scenarios
+ document well known configurations/interactions
+ test importting scenarios
+  test/document common usage

Sending to CI

### CODE REVIEW

**Comment by D10221** [comment]
Landmark: [84d74f1](https://github.com/knex/knex/pull/3985/commits/84d74f1e9ac382812d2644283e052c98555e3e0a) is a Bug fix

**Comment by kibertoad** [comment]
Beautiful. Thank you!

**Comment by kibertoad** [comment]
@D10221 Is there anything remaining from your list that you still want to do? Since this PR is already quite larged, I merged it and released another next version, but I'll wait on cutting the stable release until you feel like you are completely done.

**Comment by D10221** [comment]
@kibertoad  Thanks.
We are missing. tests for seeds/migrations module format mixes, 
Like `knexfile.js` with `seed.mjs` or or `seeds.cjs `, 'migration.cjs.js' , ... etc
Mostly for documentation reasons, of the current behaviour
But I think those cases, are edge cases.  

It feels stable, and reasonably documented from my side.

I'll be happy if users report success,

**Comment by kibertoad** [comment]
@D10221 I would say that tests for those cases are especially important for future code removal. After Node 10 is deprecated and we remove workarounds for it, would be nice to know that nothing got broken in the process.

**Comment by D10221** [comment]
> 
> 
> @D10221 I would say that tests for those cases are especially important for future code removal. After Node 10 is deprecated and we remove workarounds for it, would be nice to know that nothing got broken in the process.

Agreed, thanks.
Will add the remaining mixed format test.

It shouldn't need base code modification if there is no outstanding issues.

**Comment by D10221** [comment]
@kibertoad 
Following up here [esm_interop_test_extra_](https://github.com/D10221/knex/tree/esm_interop_test_extra_%233978_%233985)
Would you prefer me to open a PR and push to it?
Or open the PR when ready ? 
Thanks

**Comment by kibertoad** [comment]
@D10221 Pushing to PR works fine!

**Comment by D10221** [comment]
> 
> 
> @D10221 Pushing to PR works fine!

Thank, will do

**Pull request merged**
