### PR TITLE
rewrite delay to not node-only version

### PR DESCRIPTION
**Pull request by maximelkin**

### CODE REVIEW

**Comment by kibertoad** [comment]
Can you explain the reason behind this change?

**Comment by maximelkin** [comment]
Users write comments about broken delay() function when they run tests in browser environment (yeah they didn't know about it, but this is a bit tediously).
Also in readme indicated browser support.

(personally i dont think what somebody really use knex in browser, lol)

**Comment by kibertoad** [comment]
Makes sense!

**Comment by kibertoad** [comment]
Released in knex@0.21.1

**Pull request merged**
