### PR TITLE
Fix QueryBuilder.extend this type (#3526)

### LINKED ISSUE #3526: TypeScript Definitions: fix Knex.QueryBuilder.extend signature
# Environment

Knex version: 0.19.5

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Function passed to `Knex.QueryBuilder.extend` uses `this` as `QueryBuilder` . However it is typed as `Knex`.

2. Error message

TypeScript complains about `QueryBuilder` methods like `toSQL` or Promise methods like `then` when used on `this` in the extending function.

```Property 'then' does not exist on type Knex<any, any[]>```

3. Reduced test code

See https://github.com/knex/knex/issues/1355#issuecomment-551435034.

It uses `this: Knex.QueryBuilder` in function signature to fix the problem and types the fuction as `any` in the end to avoid TypeScript complaining about unassignable function types due to `Knex` and `QueryBuilder` type incompatibility.

4. Solution

The [`Knex.QueryBuilder.extend` signature](https://github.com/knex/knex/blob/master/types/index.d.ts#L1930-L1936) should use `QueryBuilder` for `this`:
```ts
static extend(
    methodName: string,
    fn: <TRecord extends {} = any, TResult = unknown[]>(
      this: QueryBuilder<TRecord, TResult>,
      ...args: any[]
    ) => QueryBuilder<TRecord, TResult>
  ): void;
```

instead of `Knex`:
```ts
static extend(
    methodName: string,
    fn: <TRecord extends {} = any, TResult = unknown[]>(
      this: Knex<TRecord, TResult>,
      ...args: any[]
    ) => QueryBuilder<TRecord, TResult>
  ): void;
```

### PR DESCRIPTION
**Pull request by iki**
@lorefnon fixes #3526

### CODE REVIEW

**Comment by lorefnon** [comment]
It seems that the test suite is failing because QueryBuilder type doesn't declare client property. 

This has been addressed in https://github.com/knex/knex/pull/3541.

**Comment by kibertoad** [comment]
@iki Could you please rebase the PR?

**Comment by kibertoad** [comment]
@lorefnon @iki 
```
Error: /home/travis/build/knex/knex/types/test.ts:14:34
ERROR: 14:34  expect  TypeScript@next compile error: 
Property 'raw' does not exist on type 'Client'.
    at /home/travis/build/knex/knex/node_modules/dtslint/bin/index.js:193:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/knex/knex/node_modules/dtslint/bin/index.js:6:58)
    at <anonymous>
```

Wonder if tests are wrong or types.

**Comment by kibertoad** [comment]
@iki Type tests are still failing.

**Comment by lorefnon** [comment]
I didnt notice that Client types are very incomplete. I can check on this tomorrow.

**Comment by lorefnon** [comment]
I couldn't take this up last week. I have added missing methods of Client type in https://github.com/knex/knex/pull/3565. 

Many of them are still incomplete because many types that Client depends on also don't have definitions. I am hoping to address this better as a part of https://github.com/knex/knex/issues/3521. 

But I have verified that that pr fixes the type errors in this one.

**Comment by kibertoad** [comment]
@iki I've merged #3565, could you please rebase now?

**Comment by iki** [comment]
@kibertoad done
@lorefnon thanks for the fix!

**Pull request merged**
