### PR TITLE
Clarify acquireConnection() signature

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by maximelkin** [comment]
@kibertoad I didn't see any place of passing config.connection, except sqlite3 ddl
so this works because config parameter for .transaction method not documented and in project this used only for sqlite3, which does not override this method

It should be safe to replace signature to correct

**Comment by kibertoad** [comment]
@maximelkin Did the change, let's see if CI passes :)

**Comment by maximelkin** [comment]
@kibertoad fails because config is optional parameter, so it can be undefined

**Comment by kibertoad** [comment]
@maximelkin You are right! Thanks, pushed the fix.

**Pull request merged**
