### PR TITLE
oracledb: commit was a no-op causing race conditions 

### LINKED ISSUE #3612: oracledb: commit is a no-op
# Environment

Knex version: 0.20.6
Database + version: Oracle 12c
OS: Linux & OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

The oracledb commit is a no-op. I think it should perform the actual commit immediately.

2. Error message

There's no error message.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

I noticed this in our production code that the commit seemed to not work immediately. The integration tests also seem to exhibit this behavior which is why it may fail sometimes (race conditions.)

Here's the code path it takes:

1. Transaction starts and it sets [isTransaction=true](https://github.com/knex/knex/blob/aea29d0a7c00a4e6e0f6eafdf57240ef211813cb/lib/dialects/oracledb/transaction.js#L60)
2. When commit is called it calls `commitAsync` which [immediately resolves doing nothing](https://github.com/knex/knex/blob/aea29d0a7c00a4e6e0f6eafdf57240ef211813cb/lib/dialects/oracledb/index.js#L112)
3. Later it sets [isTransaction=false](https://github.com/knex/knex/blob/aea29d0a7c00a4e6e0f6eafdf57240ef211813cb/lib/dialects/oracledb/transaction.js#L72) so it really does the commit this time.

The problem is in the tests and in my production code I assume the commit actually happened when commit was called, so we occasionally see errors due to the race condition it creates.

### PR DESCRIPTION
**Pull request by jakecoffman**
fix #3612

### CODE REVIEW

**Comment by kibertoad** [comment]
@akaraivanov @jakecoffman I assume this still needs new unit tests with Sinon mocks?

**Comment by kibertoad** [comment]
refs #3225

**Comment by jakecoffman** [comment]
I'm trying to see if the integration tests I enabled will fail in travis so I am running them repeatedly. Would that be enough to say that this fix is tested? It would probably be more meaningful than a mocked out db call.

**Comment by kibertoad** [comment]
Yeah, fair :)

**Comment by kibertoad** [comment]
Seem to be green, so at least not worse than before. Let's land this and observe oracle behaviour in master over longer period of time.

**Pull request merged**
