### PR TITLE
WIP: Refactor Migrator code and API to return list of migrations as objects consistently.

### PR DESCRIPTION
**Pull request by marceliwac**
Fix to issue #4719.

### CODE REVIEW

**Comment by kibertoad** [comment]
Thank you! Can you add some tests for this code?

**Comment by marceliwac** [comment]
@kibertoad Yeah, absolutely. Should have them in by tomorrow.

**Comment by kibertoad** [comment]
Why was this closed?

**Comment by marceliwac** [comment]
@kibertoad Classic Git/Github shennanigans.

I've deleted my source branch to re-upload new changes with cleaner git history (instead of force pushing to overwrite the changes, which is what I should have done).

Will be re-submitting the PR now.

**Pull request closed without merging**
