### PR TITLE
Implement extendable builders

### PR DESCRIPTION
**Pull request by DominicVonk**
Fixes issue #4555

Can you merge this? @kibertoad

### CODE REVIEW

**Comment by intech** [comment]
@DominicVonk I like your PR, but I'm sure it won't pass without tests

**Comment by OlivierCavadenti** [comment]
> @DominicVonk I like your PR, but I'm sure it won't pass without tests

you are right :D

**Comment by DominicVonk** [comment]
The unit test is added

**Comment by DominicVonk** [comment]
@OlivierCavadenti can you check the pr?

**Comment by OlivierCavadenti** [comment]
Linting and types fails @DominicVonk

**Comment by DominicVonk** [comment]
Is this planned to be merged?

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
@DominicVonk Can you also submit documentation PR to https://github.com/knex/documentation?

**Comment by creatyvtype** [comment]
When will this be released to a new version?

**Comment by kibertoad** [comment]
Released in 2.1.0

**Pull request merged**
