### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
Latest tarn.js types throw an error for pre-3.7 versions: "An accessor cannot be declared in an ambient context", so I had to bump it. @lorefnon do you think that makes sense?

**Comment by lorefnon** [comment]
I don't have any issue with bumping to TS 3.7+. 

If someone comes up with a request to support lower versions of TS we can send a PR to tarn to use [downlevel-dts](https://github.com/sandersn/downlevel-dts).

**Comment by kibertoad** [comment]
@maximelkin Looks like Node 13 is consistently failing with Oracle when newest Tarn.js is used. Any ideas?

**Comment by kibertoad** [comment]
Wait, this is the first time. Let me rerun...

**Pull request merged**
