### PR TITLE
add dropForeign arg type for single column

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by kibertoad** [comment]
@capaj 
```
  types/index.d.ts:1862:29
  ✖  1862:29  readonly type modifier is only permitted on array and tuple literal types.  
```

**Comment by capaj** [comment]
@kibertoad should be good now

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thanks!

**Comment by kibertoad** [comment]
Released in 0.95.3.

**Pull request merged**
