### PR TITLE
Throw error when specific seed file cannot be found

### LINKED ISSUE #4005: Knex seed should notify when a specific seed is not found
# Environment

Knex version: 0.21.5
Database + version: PostgreSQL: 12.4
OS: macOS 10.15.6

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am calling `knex.seed.run({ specific: 'some-seeder.ts' });` to invoke a **specific** seed file that my integration tests **rely** on.
I had renamed that seeder, and the command could not find it, but:

- did not throw an error
- did not show a warning or notice to let me know it was ignored (failed silently)

I figured out what was the problem by debugging and realizing that the seeder was not invoked at all.

2. Error message

There is none, it fails silently, this is my issue.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
// a test in a jest environment
beforeAll(async () => {
  // not finding a **specific** seeder should throw, or at least notice that the seeder cannot be executed
  await knex.seed.run({ specific: 'some-file-that-does-not-exists' });
});
```

# Feature discussion / request

1. Explain what is your use case

I have integration tests relying on a test database which I need to seed with specific data for my tests to work (reflecting the business workflow of the client I work for)

2. Explain what kind of feature would support this

An update to the `seed.run` source code to handle the case when the `specific` option is provided but the seeder cannot be found.

3. Give some API proposal, how the feature should work

I can think of a few options:
- throw an error in such a case (could also be an opt-in flag/option for `seed.run()` to throw an error in such a case)
- log a message stating that one specific seeder cannot be found

I am happy to contribute with a PR after I get some approval on the way forward :)

### PR DESCRIPTION
**Pull request by flo-sch**
fix(seed): throw error when specific seed file cannot be found

fixes #4005

### CODE REVIEW

**Comment by flo-sch** [comment]
It looks like some unrelated tests are failing on node v10:

> Should have created new connection and execute the query, got : Error: select 1 - This socket has been ended by the other party

Is that a known issue?

**Comment by elhigu** [comment]
I haven't seen that before, sounds like CI was having some issues... for some reason I don't have controls in travis to re-run CI anymore so I had to close/open to do that.

**Comment by flo-sch** [comment]
Looks like it worked this time... Not sure what happened in Travis then 🤷‍♂

**Comment by elhigu** [comment]
Thanks!

**Pull request merged**
