### PR TITLE
Add readonly transaction access mode

### PR DESCRIPTION
**Pull request by omikader**
Attempt to add the ability to make read only transactions in MySQL, Postgres, and Redshift

Documentation PR: https://github.com/knex/documentation/pull/489

### CODE REVIEW

**Review by kibertoad — CHANGES_REQUESTED** [review]
Thank you, this is excellent!

Could you please also submit a documentation update PR for https://github.com/knex/documentation, and update TS types?

**Comment by omikader** [comment]
> Thank you, this is excellent!
> 
> Could you please also submit a documentation update PR for https://github.com/knex/documentation, and update TS types?

Thanks for reviewing @kibertoad! I added a PR for the documentation but what other changes do I need for types besides the ones in `index.d.ts`?

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Sorry, somehow missed those types

**Comment by kibertoad** [comment]
Can you check the CI failures?

**Pull request merged**
