### PR TITLE
let types export Knex.TransactionConfig

### PR DESCRIPTION
**Pull request by zfben**
export `Knex.TransactionConfig`

### CODE REVIEW

**Comment by kibertoad** [comment]
Thanks! Could you also add tsd test for this import?

**Comment by zfben** [comment]
> Thanks! Could you also add tsd test for this import?

`TransactionConfig` is not a returnable type, i don't know how to use tsd test to test it, do you have any idea?

**Comment by zfben** [comment]
@kibertoad Could you merge the pr?

**Comment by kibertoad** [comment]
@zfben What do you mean by `not a returnable type`? Can't you just do `const trxConfig: Knex.TransactionConfig = {// config goes here}`?

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Thank you!

**Comment by kibertoad** [comment]
Released in 0.95.7

**Pull request merged**
