### PR TITLE
Fix: Support for `.finally(..)` on knex's Promise-alikes

### PR DESCRIPTION
**Pull request by briandamaged**

### CODE REVIEW

**Comment by kibertoad** [comment]
@briandamaged is ` knex.select(1).finally(() => console.log('huh'))` still breaking after this change?

**Comment by briandamaged** [comment]
@kibertoad : Looks like it passes.  Want me to add a unit test for that as well, or is there already one available in a separate branch?

**Comment by kibertoad** [comment]
No such test yet, so would be good to add.

**Comment by briandamaged** [comment]
@kibertoad : k -- it looks like the unit tests and such are passing now.  Should we merge it?

**Comment by kibertoad** [comment]
Yup! Thanks a lot. I'll cherry-pick and cut new 0.20.x release later today.

**Pull request merged**
