### PR TITLE
Add CI support for Oracle 18c (resolves #4888)

### LINKED ISSUE #4888: Task: Add CI support for Oracle 18c
# Feature

This is a feature ticket to track the work of implementing the below changes.

Tagging user @lorefnon since this involved oracle
Tagging issue #4869 ("Inserting Buffers for Oracle CLOBs silently fails") since its resolution is blocked on this.

## Use case

Knex CI for PRs should run full test suite again Oracle so that features may be properly validated.

## Explain what kind of feature would support this

By adding automation to this repository and using the [quillbuilduser/oracle-18-xe](https://hub.docker.com/r/quillbuilduser/oracle-18-xe) Docker container we can do a full Github Actions CI environment for Oracle 18c XE on Linux.

## Acceptance Criteria

- [x] A local Oracle 18c database can be stood up on a Linux machine using automation in this repository.
- [x] This logic is used to run CI automation on PRs via Github Actions, as is standard with all other databases supported by Knex.
- [x] All changes and use is documented.

### PR DESCRIPTION
**Pull request by code-ape**
**Status:** CI support working but 18+ tests failing (current result for oracledb is 321 passing, 18 failing, and 61 pending, fixed 16 tests that were initially failing)

**Related Issues:**
1. #4888
2. #4890

**Recommended Merge Style:** Squash, commit messages aren't super clear.

**Changes:**
1. Moved all setup logic from `.travis.yml` file into `scripts/oracledb-install-driver-libs.sh` with help menus and dry-run capability.
2. Fixed naming in `scripts/docker-compose.yml` for oracle to match testing automation logic of other databases.
3. Added oracle to CI integration tests in `.github/workflows/integration-tests.yml`
4. Sped up CI integration tests by only installing `pg-native` when testing it.
5. Sped up CI integration tests by installing npm packages while database boots.
6. Fixed CI integration setup logic by not detaching from "wait" container for database setup.
7. Fixed 16 of 34 known failing tests. (thanks @OlivierCavadenti)
8. Added temporary failure catch for CI for oracle to allow merge now and cleanup remaining failing tests in another PR.

### CODE REVIEW

**Comment by code-ape** [comment]
This PR fully addresses getting Oracle working on CI. However, as seen by tests (see here where they were run on my fork https://github.com/code-ape/knex/actions/runs/1571181356) these are dozens failing for Oracle. I leave it to maintainers on how they would like to address these and handle this merge.

**Comment by OlivierCavadenti** [comment]
Amazing work ! For tests I suggest to fix some trivial tests here if you can (i will check later too), and skip the other and make an issue to address them immediatly. Maybe some need specific work and time to solve.

**Comment by code-ape** [comment]
Thanks @OlivierCavadenti. As you've probably guessed, I'm one of those unfortunate Oracle users right now. So happy to help add some stability for it with this 😄

As for fixing tests, to be honest I have exactly zero experience with debugging knex tests. So not sure what is "trivial" and what isn't. To try and help I did create ticket #4890 to track all known failing tests in checklist format with failure summary. So hopefully that should make it easy to screen which issues should be fixed with this PR and which are larger ones to be done separately. Let me know and I'll try to work on them some this week.

**Comment by OlivierCavadenti** [comment]
> As for fixing tests, to be honest I have exactly zero experience with debugging knex tests. So not sure what is "trivial" and what isn't. 

I will quickly check this tests to see what we can do, obvioulsy it's better to fix the more we can. 
At first step, we can start to fix the maximum tests we can in this PR, and decide what we do with remaining tests in few days.

**Review by OlivierCavadenti — CHANGES_REQUESTED** [review]
- In script/stress-test we have : 

```
  oracledbxe:
    image: wnameless/oracle-xe-11g
    ports:
      - "31521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
```
Need a rename ?

- Need update package.json, especially db:start and db:start:oracle jobs.

- When I launch "docker-compose -f scripts/docker-compose.yml up --build -d oracledb && docker-compose -f scripts/docker-compose.yml up waitoracledb" I have a warning with the need to remove orphans (old containers need to be purge). Can we put the flag or no need and the user will do it manually ?

- I have instance of oracledbxe in stress-test\docker.compose.yml (line 17), knex-stress-tests.js (line 166) and reconnect-test-mysql-based-drivers.js (line 150). I think this need a rename too ?

**Comment by OlivierCavadenti** [comment]
- In this commit I fix a case with binary col : https://github.com/knex/knex/pull/4889/commits/f38e57c2a9c32f89f9be1ac008a177d688ac35f9
but to dont fail, it will need : https://github.com/knex/knex/issues/4869

- In this commit https://github.com/knex/knex/issues/4837 I fix a test and the case for OracleDB fix orderBy nulls. Need to made something for PG later.

**Comment by kibertoad** [comment]
@code-ape Can you move oracle to a separate workflow or step and mark as optional so that we can merge this now and fix tests as we go?

**Comment by code-ape** [comment]
@kibertoad sure. Do you want me to split out @OlivierCavadenti's test fix work onto a separate branch?

**Comment by kibertoad** [comment]
@code-ape Not necessary, we can merge both together to have less test failures to begin with :)

**Review by kibertoad — APPROVED** [review]

**Review by OlivierCavadenti — APPROVED** [review]

**Comment by code-ape** [comment]
Oracle test failure catch working!

**Pull request merged**
