### PR TITLE
Add binary uuid option #1778

### LINKED ISSUE #1778: knex should use binary(16) for UUID outside of PG
Currently, on databases other than PostgreSQL, knex is creating UUID tables as char(36), wasting a lot of space (and making it inconvenient to use those columns as primary keys).

knex should store UUIDs as binary(16) instead, as each UUID is a 128bit (=16 byte) number and it's only represented with 36 hex characters for convenience.

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
- Add useBinaryUuid option in 'uuid' function.
- If this option is 'true' use 'binary(16)' type (other than PG).
- Closes #1778

### CODE REVIEW

**Review by mishase — CHANGES_REQUESTED** [review]
You should create function to transform uuid-s before inserting and after get. You can use something like uuid-parse package.
For example, currently i'm are using query transformer to automatically parse uuid in readable strings for mysql db like this:
```
function typeCast(field, next) {
	if (field.type === "STRING" && field.length === 16) {
		const buf = field.buffer();
		return buf ? uuidParse.unparse(buf) : null;
	} else {
		return next();
	}
}
```
this function makes easier to work with uuid-s in backend, but limits some functionality because it will trigger to any varchar(16) columns

**Review by kibertoad — APPROVED** [review]

**Comment by OlivierCavadenti** [comment]
Ok, I see the point.
Knex include already uuid package (https://www.npmjs.com/package/uuid#uuidparsestr) so I will check later what I can do.

**Comment by OlivierCavadenti** [comment]
> You should create function to transform uuid-s before inserting and after get. You can use something like uuid-parse package. For example, currently i'm are using query transformer to automatically parse uuid in readable strings for mysql db like this:
> 
> ```
> function typeCast(field, next) {
> 	if (field.type === "STRING" && field.length === 16) {
> 		const buf = field.buffer();
> 		return buf ? uuidParse.unparse(buf) : null;
> 	} else {
> 		return next();
> 	}
> }
> ```
> 
> this function makes easier to work with uuid-s in backend, but limits some functionality because it will trigger to any varchar(16) columns

As I can see it's not so easy to make that in Knex.
I want to make something generic, where the logic of parse/unparse is defined with column definition (in ColumnCompiler).
When you prepare Insert in querycompiler you dont have any information about the column type and you cant convert your uuid at this time.
Same problem in runner.js when you process the query.
If you have hints about how to get the type of column inside insert compiler and runner I am open @kibertoad.
If it's not possible, I can also make utils to manually convert uuid's before and after inserts.

**Comment by kibertoad** [comment]
@OlivierCavadenti Knex should never have any info about column it is inserting to. I would suggest adding util method to knex-utils instead.

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Knex should never have any info about column it is inserting to. I would suggest adding util method to knex-utils instead.

One other option is to provide utils in knex (like knex.raw...) to convert in binary with database specific SQL (like BIN_TO_UUID in MYSQL: https://stackoverflow.com/a/45186851/1535159).  Need more work btw.

**Comment by kibertoad** [comment]
yeah, that works too

**Comment by intech** [comment]
In cockroachdb, pg types are used and I have to fix the answer with hexadecimal data, I temporarily did this:
```js
const { types } = require("pg");
types.setTypeParser(17, value => Buffer.from(value.replace("\\x", ""), "hex"));
```
You need to think about a more beautiful solution.

**Comment by OlivierCavadenti** [comment]
> In cockroachdb, pg types are used and I have to fix the response with hexadecimal data, I temporarily did this:
> 
> ```js
> const { types } = require("pg");
> types.setTypeParser(17, value => Buffer.from(value.replace("\\x", ""), "hex"));
> ```
> 
> We need to think about a more beautiful solution.
> 
> For insertion the uuid format can be any hex, or formatted with a separator, or guid in curly braces, all of these formats are converted automatically to the specified column type, or text representation, or binary (hex)

Thanks for comments. I need to finish another task before this PR, but as I can see, a lot of people have workaround and wait this. I will find a clean solution to make the use as smooth as possible :D.

**Comment by kibertoad** [comment]
@OlivierCavadenti BTW, can you add yourself to the list of maintainers in package.json?

**Comment by OlivierCavadenti** [comment]
I choose to add two functions in FunctionHelper.js to avoid dependencies and SQL db specific generation.

To use : 

Create table with option actived on uuid column:

```js
await knex.schema.createTable('uuid_table', (t) => {
  t.uuid('uuid_col_binary', { useBinaryUuid: true });
});
```

Insert your uuid in binary format with uuidToBin function: 

```js
await knex('uuid_table').insert({
  uuid_col_binary:  knex.fn.uuidToBin('3f06af63-a93c-11e4-9797-00505690773f'),
});
```

Retreive it and convert it:

```js
const uuid = await knex('uuid_table').select('uuid_col_binary');
knex.fn.binToUuid(uuid[0].uuid_col_binary)
```

**Comment by OlivierCavadenti** [comment]
@mishase @intech the solution is good for you (see comment above) ?

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
