### PR TITLE
dispose Oracle connection on connection error

### PR DESCRIPTION
**Pull request by jakecoffman**
added a test for PR #3537

### CODE REVIEW

**Comment by kibertoad** [comment]
Wow! Thank you so much!

**Comment by jakecoffman** [comment]
I'd like to fix #3612 too but I probably can't get to it until tomorrow.

**Comment by kibertoad** [comment]
@jakecoffman Should I wait with releasing a new version of knex until then?

**Comment by jakecoffman** [comment]
@kibertoad  It looks like there is more that I don't understand yet. You shouldn't wait for me to figure this out, might be a while! Thanks

**Comment by kibertoad** [comment]
Released in knex@0.20.7

**Pull request merged**
