### PR TITLE
Destroy should not trigger an error (Closes #4132)

### LINKED ISSUE #4132: Error: stream destroyed
# Environment

Knex version: 0.21.12
Nodejs version: 14.15.1
Database + version: MariaDB 10.3.27
OS: Centos 7

# Bug

I encountered this issue after updating knex from version 0.16.3 to version 0.21.12 and NodeJS from 6.9.0 to 14.15.1, before that I have never see this error.

1. I'm trying to retrieve a large amount of data from a SELECT statement by using the stream API:
```javascript
    return new Promise((res) => {
        let query = knex(knex.ref('table').as('l'))
            .distinct('l.*');
        query = addQueries1(query);
        query = query.where(whereFilter);
        query = addQueries2(query);
        lib.log.info('QUERYING table with: ' + query.toString());
        return query.stream(res);
    });
```
After that I simply listen on events like `stream.on('data', (chunk) => {})` or `'error'` or `'end'`. I'd like to specify that there no other call on the stream rather than the `on` listeners (neither `destroy()` or `pipe()`).
2. After some random time the stream triggers an error on the `on('error')` listener, that goes like this:
```
nov 24 10:38:55 dev2.eplate.local npm[31646]: [CHILD][PID: 32545] - [INFO] [logger] - Error: stream destroyed
nov 24 10:38:55 dev2.eplate.local npm[31646]: at Transform.destroy [as _destroy] (/opt/nodejs/eplate_nodejs/node_modules/knex/lib/runner.js:91:31)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at Transform.destroy (internal/streams/destroy.js:39:8)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at finish (_stream_writable.js:670:14)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
3. Demo code:
```javascript
const promise = new Promise(res => {
        let query = knex(knex.ref('table').as('l'))
            .distinct('l.*');
        // ensure a large set of data
        query = query.where({id: {lte: 100000}});
        lib.log.info('QUERYING table with: ' + query.toString());
        return query.stream(res);
});
promise.then(s => {
s.on('error', e => {console.error(e);});
s.on('data', c => {console.log(c);});
s.on('end', () => {console.log('end!');});
});
```

# Other details
I'm not able to reproduce this issue on a different OS...

### PR DESCRIPTION
**Pull request by danielgindi**
…ed by the transform.

Closes #4132

### CODE REVIEW

**Comment by kibertoad** [comment]
@dhensby Would it be safe to do so?

**Comment by kibertoad** [comment]
@OlivierCavadenti @elhigu Could use second opinion

**Comment by dhensby** [comment]
Hey, I don't have a super in-depth knowledge around this with tedious.

Though from my understanding of how streams work, it can be removed.

**Comment by danielgindi** [comment]
> Hey, I don't have a super in-depth knowledge around this with tedious.
> 
> Though from my understanding of how streams work, it can be removed.

Not only "can", but should. Destroy should not throw an error. It is a normal node event. There's an "error" event that is fired when there's an error. "destroy" is not that...

**Comment by dprgarner** [comment]
This commit has been cherry-picked and merged in https://github.com/knex/knex/pull/5243 .

**Pull request closed without merging**
