### PR TITLE
Migrate documentation to vitepress

### PR DESCRIPTION
**Pull request by stafyniaksacha**
This pull request is related to work made on https://github.com/knex/documentation/issues/391 and https://github.com/knex/documentation/issues/337

Preview 🪄 https://stafyniaksacha.github.io/knex/

It migrates back the documentation on this repository (with github action configured to ignore changes on the `docs` so it will not trigger them) so we benefit from the latest changelog and have one source of truth. It's opinionated, but I think it will encourage people to update documentation when they make changes (we can move this back to the other repository if needed).

All the documentation and wiki content has been migrated to markdown with latest version (v1.0.7)

- I do not have made anything related with dialect SQL output selection, but we can do it easily with custom vue components and localstorage (as on the vuejs website for the composition/option api)
- We may want to discuss the documentation sections as well!
- We can also add a great search experience easily with https://docsearch.algolia.com/apply/ 
- A lot of small improvement can be made!

### CODE REVIEW

**Comment by OlivierCavadenti** [comment]
Amazing ! I will read carefull read this PR as soon as possible, but the result seems wonderful.

**Comment by vencho-mdp** [comment]
Oh, it looks awesome!

**Comment by stafyniaksacha** [comment]
@vencho-mdp @OlivierCavadenti just pushed a darkmode :)

**Comment by vencho-mdp** [comment]
I'd like to try to add the SQL dropdown we have in the current Knex docs. It's quite nice (just as the composition and options api in vue).

**Comment by vencho-mdp** [comment]
Hi! I'm having quite a lot of problems with the installation of dependencies. In my opinion, if the docs and knex source code will be in the same repo, each should have a separate `package.json` because of this, dependencies issues. What's your opinion?

**Comment by stafyniaksacha** [comment]
> Hi! I'm having quite a lot of problems with the installation of dependencies. In my opinion, if the docs and knex source code will be in the same repo, each should have a separate `package.json` because of this, dependencies issues. What do you think?

hum, that's a good question. I think since we are not in a monorepo we should keep only one package.json. Se we can either bring back the doc to the other repo or keep the doc dependencies lean. (we may just need vueuese I think, but we can add tons of vite plugins)

**Comment by vencho-mdp** [comment]
Oh, there's already a repo for knex docs. https://github.com/knex/documentation

**Comment by intech** [comment]
### Excellent work! Let me suggest a few improvements:

**1. The color of the names is too pale. It would be best if you made it more contrast (darker)**

Screenshot from 2022-04-18 16-00-54

**2. The width of the right content column is too narrow. Why not make it fullscreen**

Screenshot from 2022-04-18 16-01-27

**Comment by stafyniaksacha** [comment]
> Excellent work! Let me suggest a few improvements:
> 
> **1. The color of the names is too pale. It would be best if you made it more contrast (darker)**
> 
> Screenshot from 2022-04-18 16-00-54

I agree with your feedback! So I updated a bit the contrast:

image

> **2. The width of the right content column is too narrow. Why not make it fullscreen**
> 
> Screenshot from 2022-04-18 16-01-27

For the width, I just augmented the max-width. As fullwidth make sentences and code samples to wide: 
image


@intech @vencho-mdp should I move this pr to https://github.com/knex/documentation ?

**Comment by OlivierCavadenti** [comment]
I think is better to keep the two repos splitted to not blend dependencies and configuration (like webpack). @kibertoad  ?

**Comment by kibertoad** [comment]
I agree, let's keep them separate.

**Comment by stafyniaksacha** [comment]
Can you create an empty `main` branch on the `documentation` repo so I can create the PR from https://github.com/stafyniaksacha/documentation/tree/main

**Comment by kibertoad** [comment]
@stafyniaksacha Empty `main` created.

**Comment by stafyniaksacha** [comment]
@kibertoad @OlivierCavadenti @intech @vencho-mdp done in https://github.com/knex/documentation/pull/400 I close this PR

**Pull request closed without merging**
